// SPDX-License-Identifier: GPL-3.0-or-later
import {
  SECRET_REF_KINDS,
  VERSIONED_FIELDS,
  type SecretRef,
  type VersionedField,
} from '../model/credential.js';
import {
  DEFAULT_HEALTH_THRESHOLDS,
  HEALTH_RULE_IDS,
  type HealthAnalysisOptions,
  type HealthRuleId,
  type HealthThresholds,
} from '../model/health.js';
import type { HistoryPointRef } from '../model/history.js';

/**
 * Runtime validation for everything crossing IPC.
 *
 * TypeScript is erased at runtime. A handler typed `(path: string)` will happily receive
 * `undefined`, an object, or a 40 MB string, and the first sign of trouble will be a
 * confusing error somewhere much deeper. For a process that holds every one of the user's
 * passwords, "trust the type annotation" is not a security posture.
 *
 * These validators are deliberately small, dependency-free and total: every one returns a
 * value or throws, and none of them can partially succeed.
 *
 * Written by hand rather than with a schema library because the surface is tiny, the
 * failure messages want to be specific, and a validator with no dependencies is one fewer
 * package in the trust boundary that guards the vault.
 */

export class IpcValidationError extends Error {
  readonly channel: string;

  constructor(channel: string, detail: string) {
    // Never interpolate the offending value — it could be a password, and this message
    // is destined for a log.
    super(`Invalid IPC payload on ${channel}: ${detail}`);
    this.name = 'IpcValidationError';
    this.channel = channel;
  }
}

/**
 * Caps every incoming string.
 *
 * Without a cap, one `ipcRenderer.invoke` carrying a 500 MB string is a trivial
 * out-of-memory attack from a compromised renderer. Generous enough for a long passphrase
 * or a pasted note, small enough to be harmless.
 */
export const MAX_STRING_BYTES = 1_048_576; // 1 MiB

export function requireString(channel: string, value: unknown, name: string): string {
  if (typeof value !== 'string') {
    throw new IpcValidationError(channel, `${name} must be a string`);
  }
  if (value.length > MAX_STRING_BYTES) {
    throw new IpcValidationError(channel, `${name} exceeds the ${MAX_STRING_BYTES}-byte limit`);
  }
  return value;
}

export function requireNonEmptyString(channel: string, value: unknown, name: string): string {
  const text = requireString(channel, value, name);
  if (text.trim() === '') throw new IpcValidationError(channel, `${name} must not be empty`);
  return text;
}

/**
 * Ids are generated by us and are always UUIDs or hex chunk ids.
 *
 * Constraining the character set means an id can never carry a path traversal, a
 * separator, or anything else that changes meaning when it is later interpolated.
 */
const ID_PATTERN = /^[A-Za-z0-9_-]{1,128}$/;

export function requireId(channel: string, value: unknown, name: string): string {
  const text = requireString(channel, value, name);
  if (!ID_PATTERN.test(text)) {
    throw new IpcValidationError(channel, `${name} is not a valid identifier`);
  }
  return text;
}

export function requireBoolean(channel: string, value: unknown, name: string): boolean {
  if (typeof value !== 'boolean') {
    throw new IpcValidationError(channel, `${name} must be a boolean`);
  }
  return value;
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * Validates a `SecretRef` — the most security-sensitive payload in the whole contract.
 *
 * This is what stands between "reveal my GitHub password" and "reveal an arbitrary
 * property of an arbitrary object". The union is closed, every branch names its required
 * fields, and an unknown `kind` is rejected outright rather than falling through to a
 * default.
 */
export function requireSecretRef(channel: string, value: unknown): SecretRef {
  if (!isPlainObject(value)) throw new IpcValidationError(channel, 'ref must be an object');

  const kind = value.kind;
  if (typeof kind !== 'string' || !(SECRET_REF_KINDS as readonly string[]).includes(kind)) {
    throw new IpcValidationError(channel, 'ref.kind is not a known secret kind');
  }

  const credentialId = requireId(channel, value.credentialId, 'ref.credentialId');
  // Read lazily: the live kinds carry no version number, and demanding one up front would
  // reject every ordinary reveal.
  const version = (): number =>
    requireVersionNumber(channel, value.versionNumber, 'ref.versionNumber');

  switch (kind as SecretRef['kind']) {
    case 'password':
      return { kind: 'password', credentialId };
    case 'notes':
      return { kind: 'notes', credentialId };
    case 'security-answer':
      return {
        kind: 'security-answer',
        credentialId,
        questionId: requireId(channel, value.questionId, 'ref.questionId'),
      };
    case 'custom-value':
      return {
        kind: 'custom-value',
        credentialId,
        fieldId: requireId(channel, value.fieldId, 'ref.fieldId'),
      };
    case 'historic-password':
      return { kind: 'historic-password', credentialId, versionNumber: version() };
    case 'historic-notes':
      return { kind: 'historic-notes', credentialId, versionNumber: version() };
    case 'historic-answer':
      return {
        kind: 'historic-answer',
        credentialId,
        versionNumber: version(),
        questionId: requireId(channel, value.questionId, 'ref.questionId'),
      };
    case 'historic-custom':
      return {
        kind: 'historic-custom',
        credentialId,
        versionNumber: version(),
        fieldId: requireId(channel, value.fieldId, 'ref.fieldId'),
      };
  }
}

export interface ListOptions {
  readonly includeTrashed: boolean;
}

export function requireListOptions(channel: string, value: unknown): ListOptions {
  if (value === undefined || value === null) return { includeTrashed: false };
  if (!isPlainObject(value)) throw new IpcValidationError(channel, 'options must be an object');

  const includeTrashed = value.includeTrashed;
  return {
    includeTrashed:
      includeTrashed === undefined
        ? false
        : requireBoolean(channel, includeTrashed, 'includeTrashed'),
  };
}

/**
 * Validates a filesystem path arriving from the renderer.
 *
 * The renderer never picks a path itself — paths come from a native file dialog the main
 * process opened. This is defence in depth for the case where that stops being true, or
 * where a compromised renderer replays a channel directly.
 */
export function requireVaultPath(channel: string, value: unknown): string {
  const path = requireNonEmptyString(channel, value, 'path');
  if (path.includes('\0')) {
    // A NUL byte truncates the path in some native calls — a classic way to make a
    // validated string mean something different by the time it reaches the filesystem.
    throw new IpcValidationError(channel, 'path contains a null byte');
  }
  return path;
}

// ── History and health ───────────────────────────────────────────────────────

/**
 * Version numbers are positive integers and nothing else.
 *
 * A float, a negative or a `NaN` sails through `typeof value === 'number'` and then matches
 * no real version — which presents as "that version was pruned" rather than "the renderer
 * sent something malformed". They are different bugs and should not look the same.
 */
export function requireVersionNumber(channel: string, value: unknown, name: string): number {
  if (typeof value !== 'number' || !Number.isInteger(value) || value < 1) {
    throw new IpcValidationError(channel, `${name} must be a positive whole number`);
  }
  return value;
}

/** A point in a timeline: a version number, or the live record. */
export function requireHistoryPoint(
  channel: string,
  value: unknown,
  name: string
): HistoryPointRef {
  if (value === 'current') return 'current';
  return requireVersionNumber(channel, value, name);
}

export function requireVersionedField(channel: string, value: unknown): VersionedField {
  if (typeof value !== 'string' || !(VERSIONED_FIELDS as readonly string[]).includes(value)) {
    // Rejected rather than ignored: a restore addressed at an unknown field would silently
    // do nothing, and "the button did nothing" is the hardest kind of bug to report.
    throw new IpcValidationError(channel, 'field is not a versioned field');
  }
  return value as VersionedField;
}

/**
 * Health options, minus `now` — the clock belongs to the main process.
 *
 * Rule ids and threshold names are checked against the model rather than accepted as a
 * free-form record, so a typo disables nothing silently and an unexpected key cannot ride
 * along into the analysis.
 */
export function requireHealthOptions(
  channel: string,
  value: unknown
): Omit<HealthAnalysisOptions, 'now'> {
  if (value === undefined || value === null) return {};
  if (typeof value !== 'object' || Array.isArray(value)) {
    throw new IpcValidationError(channel, 'options must be an object');
  }

  const source = value as Record<string, unknown>;
  const options: {
    enabledRules?: Partial<Record<HealthRuleId, boolean>>;
    thresholds?: Partial<HealthThresholds>;
  } = {};

  if (source.enabledRules !== undefined) {
    const rules: Partial<Record<HealthRuleId, boolean>> = {};
    if (typeof source.enabledRules !== 'object' || source.enabledRules === null) {
      throw new IpcValidationError(channel, 'enabledRules must be an object');
    }
    for (const [key, enabled] of Object.entries(source.enabledRules as Record<string, unknown>)) {
      if (!(HEALTH_RULE_IDS as readonly string[]).includes(key)) {
        throw new IpcValidationError(channel, `"${key}" is not a health rule`);
      }
      rules[key as HealthRuleId] = requireBoolean(channel, enabled, `enabledRules.${key}`);
    }
    options.enabledRules = rules;
  }

  if (source.thresholds !== undefined) {
    if (typeof source.thresholds !== 'object' || source.thresholds === null) {
      throw new IpcValidationError(channel, 'thresholds must be an object');
    }
    const thresholds: Partial<HealthThresholds> = {};
    const allowed = Object.keys(DEFAULT_HEALTH_THRESHOLDS);
    for (const [key, threshold] of Object.entries(source.thresholds as Record<string, unknown>)) {
      if (!allowed.includes(key)) {
        throw new IpcValidationError(channel, `"${key}" is not a health threshold`);
      }
      if (typeof threshold !== 'number' || !Number.isFinite(threshold) || threshold < 0) {
        throw new IpcValidationError(channel, `thresholds.${key} must be a non-negative number`);
      }
      (thresholds as Record<string, number>)[key] = threshold;
    }
    options.thresholds = thresholds;
  }

  return options;
}
