// SPDX-License-Identifier: GPL-3.0-or-later
import { isLocalPath } from '../model/local-path.js';
import { isTagColour, TAG_COLOUR_TOKENS, type TagColour } from '../model/organisation.js';
import {
  SECRET_REF_KINDS,
  VERSIONED_FIELDS,
  type SecretRef,
  type VersionedField,
} from '../model/credential.js';
import {
  DEFAULT_HEALTH_THRESHOLDS,
  HEALTH_RULE_IDS,
  type HealthAnalysisOptions,
  type HealthRuleId,
  type HealthThresholds,
} from '../model/health.js';
import type { HistoryPointRef } from '../model/history.js';

/**
 * Runtime validation for everything crossing IPC.
 *
 * TypeScript is erased at runtime. A handler typed `(path: string)` will happily receive
 * `undefined`, an object, or a 40 MB string, and the first sign of trouble will be a
 * confusing error somewhere much deeper. For a process that holds every one of the user's
 * passwords, "trust the type annotation" is not a security posture.
 *
 * These validators are deliberately small, dependency-free and total: every one returns a
 * value or throws, and none of them can partially succeed.
 *
 * Written by hand rather than with a schema library because the surface is tiny, the
 * failure messages want to be specific, and a validator with no dependencies is one fewer
 * package in the trust boundary that guards the vault.
 */

export class IpcValidationError extends Error {
  readonly channel: string;

  constructor(channel: string, detail: string) {
    // Never interpolate the offending value — it could be a password, and this message
    // is destined for a log.
    super(`Invalid IPC payload on ${channel}: ${detail}`);
    this.name = 'IpcValidationError';
    this.channel = channel;
  }
}

/**
 * Caps every incoming string, in **UTF-16 code units** — `String.prototype.length`, not bytes.
 *
 * Without a cap, one `ipcRenderer.invoke` carrying a 500 MB string is a trivial
 * out-of-memory attack from a compromised renderer. Generous enough for a long passphrase
 * or a pasted note, small enough to be harmless.
 *
 * Named `MAX_STRING_BYTES` until finding S11, which is the kind of name that is wrong in a
 * direction that matters: a reader budgeting memory from it would be out by up to 4× on
 * astral-plane text, where one code unit is a surrogate half and the UTF-8 encoding of the
 * pair is four bytes. A million such units is about 4 MiB of UTF-8 and about 2 MiB in V8's
 * heap.
 *
 * The unit stays what it was rather than the name being made true by measuring bytes.
 * `.length` is O(1) and runs on every string crossing the bridge; `Buffer.byteLength` would
 * encode the whole string to count it, which is real work done on the exact input an attacker
 * chooses the size of — a cap that costs more the larger the payload is a worse cap. Four
 * megabytes still bounds the attack, which is all this is for.
 */
export const MAX_STRING_UNITS = 1_048_576; // 2^20 UTF-16 code units; ≤ 4 MiB of UTF-8

export function requireString(channel: string, value: unknown, name: string): string {
  if (typeof value !== 'string') {
    throw new IpcValidationError(channel, `${name} must be a string`);
  }
  if (value.length > MAX_STRING_UNITS) {
    throw new IpcValidationError(
      channel,
      `${name} is longer than the ${MAX_STRING_UNITS}-character limit`
    );
  }
  return value;
}

export function requireNonEmptyString(channel: string, value: unknown, name: string): string {
  const text = requireString(channel, value, name);
  if (text.trim() === '') throw new IpcValidationError(channel, `${name} must not be empty`);
  return text;
}

/**
 * A non-empty string with a cap tighter than the global one.
 *
 * `requireString`'s `MAX_STRING_UNITS` is the ceiling that stops a payload being a denial of
 * service; this is for a field that has a *meaning*-driven limit as well, like a saved
 * search's name. Both apply, and this one refuses rather than truncating: silently storing a
 * shortened name the user never chose is the failure that looks like the app being broken,
 * whereas a refusal says what happened.
 */
export function requireBoundedString(
  channel: string,
  value: unknown,
  name: string,
  max: number
): string {
  const text = requireNonEmptyString(channel, value, name);
  if (text.length > max) {
    throw new IpcValidationError(
      channel,
      `${name} is longer than the ${String(max)}-character limit`
    );
  }
  return text;
}

/**
 * Ids are generated by us and are always UUIDs or hex chunk ids.
 *
 * Constraining the character set means an id can never carry a path traversal, a
 * separator, or anything else that changes meaning when it is later interpolated.
 */
const ID_PATTERN = /^[A-Za-z0-9_-]{1,128}$/;

export function requireId(channel: string, value: unknown, name: string): string {
  const text = requireString(channel, value, name);
  if (!ID_PATTERN.test(text)) {
    throw new IpcValidationError(channel, `${name} is not a valid identifier`);
  }
  return text;
}

export function requireBoolean(channel: string, value: unknown, name: string): boolean {
  if (typeof value !== 'boolean') {
    throw new IpcValidationError(channel, `${name} must be a boolean`);
  }
  return value;
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * Validates a `SecretRef` — the most security-sensitive payload in the whole contract.
 *
 * This is what stands between "reveal my GitHub password" and "reveal an arbitrary
 * property of an arbitrary object". The union is closed, every branch names its required
 * fields, and an unknown `kind` is rejected outright rather than falling through to a
 * default.
 */
export function requireSecretRef(channel: string, value: unknown): SecretRef {
  if (!isPlainObject(value)) throw new IpcValidationError(channel, 'ref must be an object');

  const kind = value.kind;
  if (typeof kind !== 'string' || !(SECRET_REF_KINDS as readonly string[]).includes(kind)) {
    throw new IpcValidationError(channel, 'ref.kind is not a known secret kind');
  }

  const credentialId = requireId(channel, value.credentialId, 'ref.credentialId');
  // Read lazily: the live kinds carry no version number, and demanding one up front would
  // reject every ordinary reveal.
  const version = (): number =>
    requireVersionNumber(channel, value.versionNumber, 'ref.versionNumber');

  switch (kind as SecretRef['kind']) {
    case 'password':
      return { kind: 'password', credentialId };
    case 'notes':
      return { kind: 'notes', credentialId };
    case 'security-answer':
      return {
        kind: 'security-answer',
        credentialId,
        questionId: requireId(channel, value.questionId, 'ref.questionId'),
      };
    case 'totp-code':
      return {
        kind: 'totp-code',
        credentialId,
        fieldId: requireId(channel, value.fieldId, 'ref.fieldId'),
      };
    case 'custom-value':
      return {
        kind: 'custom-value',
        credentialId,
        fieldId: requireId(channel, value.fieldId, 'ref.fieldId'),
      };
    case 'historic-password':
      return { kind: 'historic-password', credentialId, versionNumber: version() };
    case 'historic-notes':
      return { kind: 'historic-notes', credentialId, versionNumber: version() };
    case 'historic-answer':
      return {
        kind: 'historic-answer',
        credentialId,
        versionNumber: version(),
        questionId: requireId(channel, value.questionId, 'ref.questionId'),
      };
    case 'historic-custom':
      return {
        kind: 'historic-custom',
        credentialId,
        versionNumber: version(),
        fieldId: requireId(channel, value.fieldId, 'ref.fieldId'),
      };
    case 'attachment':
      return {
        kind: 'attachment',
        credentialId,
        attachmentId: requireId(channel, value.attachmentId, 'ref.attachmentId'),
      };
  }
}

export interface ListOptions {
  readonly includeTrashed: boolean;
}

export function requireListOptions(channel: string, value: unknown): ListOptions {
  if (value === undefined || value === null) return { includeTrashed: false };
  if (!isPlainObject(value)) throw new IpcValidationError(channel, 'options must be an object');

  const includeTrashed = value.includeTrashed;
  return {
    includeTrashed:
      includeTrashed === undefined
        ? false
        : requireBoolean(channel, includeTrashed, 'includeTrashed'),
  };
}

const VAULT_EXTENSION = /\.keep$/i;

/**
 * Validates a filesystem path arriving from the renderer.
 *
 * The renderer never picks a path itself — paths come from a native file dialog the main
 * process opened. This is defence in depth for the case where that stops being true, or
 * where a compromised renderer replays a channel directly.
 */
export function requireVaultPath(channel: string, value: unknown): string {
  const path = requireNonEmptyString(channel, value, 'path');
  if (path.includes('\0')) {
    // A NUL byte truncates the path in some native calls — a classic way to make a
    // validated string mean something different by the time it reaches the filesystem.
    throw new IpcValidationError(channel, 'path contains a null byte');
  }

  // Absolute, and named like a vault.
  //
  // Without these, this validator did not defend the case its own comment names.
  // `kh:vault:create` passes the path straight to `writeVaultFileAtomically`, whose
  // first act is `mkdir(directory, { recursive: true })` — so a compromised renderer
  // replaying the channel could create arbitrary directory trees and drop a file
  // anywhere the user can write: a Startup folder, a dotfile, a config path. The dialog
  // handler already produces absolute `.keep` paths, so this costs the real flow nothing.
  //
  // `isLocalPath`, not "is it absolute": this used to accept a UNC share, and a UNC share
  // is not a place on this machine. Opening one makes the main process dial an SMB host the
  // sender chose and hand over an NTLMv2 handshake -- which a compromised renderer replaying
  // this channel would find a very cheap way to exfiltrate the user's Windows credentials.
  // One predicate, shared with the OS-side check in `src/main/shell/file-open-request.ts`,
  // because two answers to "is this path safe to touch" is two answers to disagree.
  if (!isLocalPath(path)) {
    throw new IpcValidationError(channel, 'path must be an absolute path on this machine');
  }
  if (!VAULT_EXTENSION.test(path)) {
    throw new IpcValidationError(channel, 'path must name a .keep vault file');
  }
  return path;
}

// ── History and health ───────────────────────────────────────────────────────

/**
 * Version numbers are positive integers and nothing else.
 *
 * A float, a negative or a `NaN` sails through `typeof value === 'number'` and then matches
 * no real version — which presents as "that version was pruned" rather than "the renderer
 * sent something malformed". They are different bugs and should not look the same.
 */
export function requireVersionNumber(channel: string, value: unknown, name: string): number {
  if (typeof value !== 'number' || !Number.isInteger(value) || value < 1) {
    throw new IpcValidationError(channel, `${name} must be a positive whole number`);
  }
  return value;
}

/** A point in a timeline: a version number, or the live record. */
export function requireHistoryPoint(
  channel: string,
  value: unknown,
  name: string
): HistoryPointRef {
  if (value === 'current') return 'current';
  return requireVersionNumber(channel, value, name);
}

export function requireVersionedField(channel: string, value: unknown): VersionedField {
  if (typeof value !== 'string' || !(VERSIONED_FIELDS as readonly string[]).includes(value)) {
    // Rejected rather than ignored: a restore addressed at an unknown field would silently
    // do nothing, and "the button did nothing" is the hardest kind of bug to report.
    throw new IpcValidationError(channel, 'field is not a versioned field');
  }
  return value as VersionedField;
}

/**
 * Health options, minus `now` — the clock belongs to the main process.
 *
 * Rule ids and threshold names are checked against the model rather than accepted as a
 * free-form record, so a typo disables nothing silently and an unexpected key cannot ride
 * along into the analysis.
 */
export function requireHealthOptions(
  channel: string,
  value: unknown
): Omit<HealthAnalysisOptions, 'now'> {
  if (value === undefined || value === null) return {};
  if (typeof value !== 'object' || Array.isArray(value)) {
    throw new IpcValidationError(channel, 'options must be an object');
  }

  const source = value as Record<string, unknown>;
  const options: {
    enabledRules?: Partial<Record<HealthRuleId, boolean>>;
    thresholds?: Partial<HealthThresholds>;
  } = {};

  if (source.enabledRules !== undefined) {
    const rules: Partial<Record<HealthRuleId, boolean>> = {};
    if (typeof source.enabledRules !== 'object' || source.enabledRules === null) {
      throw new IpcValidationError(channel, 'enabledRules must be an object');
    }
    for (const [key, enabled] of Object.entries(source.enabledRules as Record<string, unknown>)) {
      if (!(HEALTH_RULE_IDS as readonly string[]).includes(key)) {
        throw new IpcValidationError(channel, `"${key}" is not a health rule`);
      }
      rules[key as HealthRuleId] = requireBoolean(channel, enabled, `enabledRules.${key}`);
    }
    options.enabledRules = rules;
  }

  if (source.thresholds !== undefined) {
    if (typeof source.thresholds !== 'object' || source.thresholds === null) {
      throw new IpcValidationError(channel, 'thresholds must be an object');
    }
    const thresholds: Partial<HealthThresholds> = {};
    const allowed = Object.keys(DEFAULT_HEALTH_THRESHOLDS);
    for (const [key, threshold] of Object.entries(source.thresholds as Record<string, unknown>)) {
      if (!allowed.includes(key)) {
        throw new IpcValidationError(channel, `"${key}" is not a health threshold`);
      }
      if (typeof threshold !== 'number' || !Number.isFinite(threshold) || threshold < 0) {
        throw new IpcValidationError(channel, `thresholds.${key} must be a non-negative number`);
      }
      (thresholds as Record<string, number>)[key] = threshold;
    }
    options.thresholds = thresholds;
  }

  return options;
}

// ── Folders and tags ─────────────────────────────────────────────────────────

/** An id, or `null` for "the top level" / "no folder". Both are meaningful, `undefined` is not. */
export function requireNullableId(channel: string, value: unknown, name: string): string | null {
  if (value === null) return null;
  return requireId(channel, value, name);
}

/** A position among siblings. Bounded because it indexes an array the caller supplies. */
/**
 * A vault generation number.
 *
 * Separate from {@link requireIndex}, which caps at 10,000 because it validates a *position*
 * in a list. A generation counts saves over the life of a vault, and a vault someone actually
 * uses passes 10,000 saves — at which point an undo request would start being refused as a
 * malformed position, on a channel whose whole job is to refuse only when the vault has
 * genuinely moved on. A bound that expires quietly and turns a safety check into a bug is
 * worse than no bound.
 *
 * Bounded at `Number.MAX_SAFE_INTEGER` instead, which is where the arithmetic stops being
 * exact and so is the only ceiling that means anything.
 */
export function requireGeneration(channel: string, value: unknown, name: string): number {
  if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < 0) {
    throw new IpcValidationError(channel, `${name} is not a valid vault generation`);
  }
  return value;
}

export function requireIndex(channel: string, value: unknown, name: string): number {
  if (typeof value !== 'number' || !Number.isInteger(value) || value < 0 || value > 10_000) {
    throw new IpcValidationError(channel, `${name} is not a valid position`);
  }
  return value;
}

/**
 * What happens to a deleted folder's contents.
 *
 * Rejected rather than defaulted, deliberately. The two policies move a user's records to
 * different places, and guessing which one they meant is a data-placement decision made on
 * their behalf — the one thing this operation exists to ask them.
 */
/**
 * A tag colour, against the one list.
 *
 * The boundary used to take any string and let `setTagColour` throw `INVALID_TAG_COLOUR`
 * several layers down. That worked, in the sense that a bad colour was refused -- but it
 * refused it as an engine error rather than a malformed request, which means the message
 * that reaches the user is about their vault rather than about the value, and the main
 * process logs a stack for what is really a validation failure.
 *
 * More to the point, it was the boundary declining to check something it has the vocabulary
 * for. `TAG_COLOUR_TOKENS` is right there, shared by both processes precisely so this can be
 * one comparison.
 */
export function requireTagColour(channel: string, value: unknown): TagColour {
  if (!isTagColour(value)) {
    throw new IpcValidationError(channel, `colour must be one of: ${TAG_COLOUR_TOKENS.join(', ')}`);
  }
  return value;
}

export function requireFolderDeletePolicy(channel: string, value: unknown): 'reparent' | 'unfile' {
  if (value !== 'reparent' && value !== 'unfile') {
    throw new IpcValidationError(channel, 'policy must be "reparent" or "unfile"');
  }
  return value;
}
