// SPDX-License-Identifier: GPL-3.0-or-later
import { MAX_RANGE_BODY_BYTES } from './range.js';
import { parseRetryAfterSeconds, type BreachTransport, type RangeResponse } from './transport.js';

/**
 * **The only module in Keyhold that makes a network request.**
 *
 * Everything else in the application works with the cable pulled out, and this file is the
 * one exception — the opt-in Have I Been Pwned range lookup. It is deliberately isolated
 * into a file of its own so that "does Keyhold talk to the internet?" is answerable by
 * reading one short file, and so that nothing can acquire the ability to make a request by
 * importing something that merely sounds harmless. `client.ts` does not import this module;
 * only the composition root that acts on the user's setting does.
 *
 * `no-network.test.ts` asserts that no other file in `src/main/breach/` names `fetch`.
 *
 * ## Add-Padding, and why omitting it would be a real weakness
 *
 * Without padding, the response to a range request is as long as that range's entry list,
 * and every range has a different, publicly known length. An observer who can see the size
 * of an encrypted response — which TLS does not hide — can therefore narrow, and often
 * uniquely determine, which prefix was requested, undoing a good part of the k-anonymity
 * this feature rests on.
 *
 * `Add-Padding: true` makes the service pad every response with randomly generated
 * suffixes, each carrying a count of `0`, so responses are of a uniform, uninformative
 * size. It costs nothing, it is supported for exactly this purpose, and leaving it off is a
 * documented weakness rather than a missing nicety. `https-transport.test.ts` asserts the
 * header is sent on every request, because a header that is silently dropped fails invisibly
 * — the answers stay correct while the privacy property quietly stops holding.
 *
 * ## The rest of the request, and why each part is there
 *
 * - **`GET`, one fixed origin, no path built from user input.** The prefix is validated
 *   against a hex pattern before it is placed in the URL, so nothing can traverse out of
 *   the endpoint or append a query even if a caller passes something odd.
 * - **`redirect: 'error'`.** A redirect is a request to a host we did not choose. There is
 *   no legitimate reason for this endpoint to move mid-request, and following one would
 *   send the prefix somewhere unaudited.
 * - **`credentials: 'omit'`, `referrer: ''`.** No cookie is sent or stored and no referrer
 *   is offered. There is no session here and there must never appear to be one. There is
 *   deliberately no `cache: 'no-store'`: Node's `fetch` keeps no HTTP cache at all, so
 *   there is nothing to disable, and the option is not even in its type.
 * - **A version-free User-Agent.** The API asks callers to identify themselves and it is
 *   fair to do so. It says `Keyhold` and nothing more: a version string would narrow an
 *   observer's view of *which* Keyhold user this is, and the whole point of the exercise is
 *   to be one of a crowd.
 * - **A capped body read.** The response is streamed and stops at one byte past
 *   `MAX_RANGE_BODY_BYTES`, so a hostile or broken endpoint cannot make the process
 *   allocate without bound. The over-long body is then rejected by `parseRangeBody` as
 *   `oversized` — an `unknown` result, never a clean one.
 */

/** The free, unauthenticated k-anonymity endpoint. No key, no account, no cost. */
export const PWNED_RANGE_ENDPOINT = 'https://api.pwnedpasswords.com/range/';

/**
 * Sent on every request. See the header: this is a privacy control, not a formality.
 *
 * Exported so the test can assert it by name rather than by a string typed twice — a
 * padding header that is asserted against a copy of itself proves nothing.
 */
export const ADD_PADDING_HEADER = 'Add-Padding';

/** Identifies the client without narrowing which client. */
export const USER_AGENT = 'Keyhold';

/** Belt and braces: the prefix is generated by us, and is still validated before use. */
const PREFIX_PATTERN = /^[0-9A-F]{5}$/;

/**
 * Reads at most `MAX_RANGE_BODY_BYTES + 1` characters of the body.
 *
 * The extra character is what lets the parser tell "exactly at the cap" from "over it",
 * so an over-long response is rejected rather than silently truncated into something that
 * still parses. A truncated body that parses is the dangerous outcome: the missing tail
 * could be the very entry we were looking for.
 */
async function readCappedText(response: Response): Promise<string> {
  // Annotated rather than inferred: Node types `Response.body` as `ReadableStream<any>`, and
  // taking that inference would make every chunk an `any` flowing into the decoder — the one
  // place in this file where a hostile response's bytes are handled.
  const body: ReadableStream<Uint8Array> | null = response.body;
  if (body === null) return '';

  const reader = body.getReader();
  const decoder = new TextDecoder();
  let text = '';

  try {
    for (;;) {
      // Not destructured, so that `done` still narrows `value` for the decoder below.
      const chunk = await reader.read();
      if (chunk.done) break;
      text += decoder.decode(chunk.value, { stream: true });
      if (text.length > MAX_RANGE_BODY_BYTES) return text;
    }
  } finally {
    // Releasing the lock lets the connection be torn down promptly when we stopped early.
    reader.releaseLock();
    if (!response.bodyUsed) await body.cancel().catch(() => undefined);
  }

  return text + decoder.decode();
}

/**
 * The real transport. Constructed only when the user has turned the check on.
 *
 * A plain function rather than a class: it has no state, nothing to configure, and nothing
 * to remember between requests. Anything it remembered would be something an observer could
 * use to link two lookups together.
 */
export function createHttpsTransport(): BreachTransport {
  return {
    async fetchRange(prefix: string, signal: AbortSignal): Promise<RangeResponse> {
      if (!PREFIX_PATTERN.test(prefix)) {
        // Not a user-facing error: this can only fire if a caller bypassed `rangePrefix`.
        // The message names the expected shape, never the value it was given.
        throw new TypeError('A range prefix must be five upper-case hex characters.');
      }

      const response = await fetch(`${PWNED_RANGE_ENDPOINT}${prefix}`, {
        method: 'GET',
        headers: {
          // The privacy control. See the file header.
          [ADD_PADDING_HEADER]: 'true',
          Accept: 'text/plain',
          'User-Agent': USER_AGENT,
        },
        redirect: 'error',
        credentials: 'omit',
        referrer: '',
        signal,
      });

      const retryAfterSeconds = parseRetryAfterSeconds(
        response.headers.get('retry-after'),
        Date.now()
      );

      // Only a 200 has a body worth reading. Reading a 500's HTML error page would
      // allocate for nothing and put an attacker-influenced blob in memory next to a
      // prefix, for no benefit at all.
      const body = response.status === 200 ? await readCappedText(response) : '';

      return { status: response.status, body, retryAfterSeconds };
    },
  };
}
